### ISSUE TITLE
compile problem with scotch

### ISSUE THREAD

**Issue by nuaawqf** [GEM3D/rebl-AMR-V2-#1]
Dear developers:

I am using Ubuntu 16.04 LTS, gcc 5.4.0, openmpi 2.0.1 , parmetis 4.0.3 hdf5-1.8.16, and Zoltan-3.83. And I use scotch5.1.9 and parmetis 3.1 for zoltan compilation. 
I have met this compile problem when compiling amrGem:

[100%] Linking CXX executable ../bin/amrGem
/home/nuaawqf/Zoltan-3.83/build/src/libzoltan.a(scotch_interface.o): In function `Zoltan_Scotch_Build_Graph':
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:971: undefined reference to `SCOTCH_dgraphInit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:979: undefined reference to `SCOTCH_dgraphBuild'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:982: undefined reference to `SCOTCH_dgraphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:989: undefined reference to `SCOTCH_graphInit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:993: undefined reference to `SCOTCH_graphBuild'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:1000: undefined reference to `SCOTCH_stratInit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:995: undefined reference to `SCOTCH_graphExit'
/home/nuaawqf/Zoltan-3.83/build/src/libzoltan.a(scotch_interface.o): In function `Zoltan_Scotch_Order':
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:262: undefined reference to `SCOTCH_stratDgraphOrder'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:264: undefined reference to `SCOTCH_stratGraphOrder'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:329: undefined reference to `SCOTCH_graphOrder'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:481: undefined reference to `SCOTCH_dgraphOrderExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:482: undefined reference to `SCOTCH_dgraphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:489: undefined reference to `SCOTCH_stratExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:376: undefined reference to `SCOTCH_dgraphOrderPerm'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:383: undefined reference to `SCOTCH_dgraphOrderCblkDist'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:408: undefined reference to `SCOTCH_dgraphOrderTreeDist'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:487: undefined reference to `SCOTCH_graphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:308: undefined reference to `SCOTCH_dgraphOrderInit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:321: undefined reference to `SCOTCH_dgraphOrderCompute'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:266: undefined reference to `SCOTCH_dgraphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:269: undefined reference to `SCOTCH_graphExit'
/home/nuaawqf/Zoltan-3.83/build/src/libzoltan.a(scotch_interface.o): In function `Zoltan_Scotch':
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:742: undefined reference to `SCOTCH_stratGraphMap'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:762: undefined reference to `SCOTCH_graphStat'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:771: undefined reference to `SCOTCH_archInit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:772: undefined reference to `SCOTCH_archCmpltw'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:778: undefined reference to `SCOTCH_dgraphMap'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:812: undefined reference to `SCOTCH_dgraphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:819: undefined reference to `SCOTCH_archExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:759: undefined reference to `SCOTCH_dgraphSize'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:740: undefined reference to `SCOTCH_stratDgraphMap'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:744: undefined reference to `SCOTCH_dgraphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:797: undefined reference to `SCOTCH_graphMap'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:817: undefined reference to `SCOTCH_graphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:747: undefined reference to `SCOTCH_graphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:798: undefined reference to `SCOTCH_archExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:800: undefined reference to `SCOTCH_graphExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:785: undefined reference to `SCOTCH_archExit'
/home/nuaawqf/Zoltan-3.83/build/src/../../src/tpls/scotch_interface.c:787: undefined reference to `SCOTCH_dgraphExit'
collect2: error: ld returned 1 exit status
CMakeFiles/amrGem.dir/build.make:437: recipe for target '../bin/amrGem' failed
make[2]: *** [../bin/amrGem] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/amrGem.dir/all' failed
make[1]: *** [CMakeFiles/amrGem.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I have tested my Zoltan with examples both in C and CPP. I think the libzoltan.a is compiled successfully. But I cannot tell whether this error is related to my scotch or something else. Can you help me with this?

Thanks,

Qifeng

**Comment by Jaberh** [comment]
Hi nuaawqf 
Were you able to resolve your issue? can you explain what the problem was? 
thanks

**Comment by nuaawqf** [comment]
Hi Jaberh:

Thanks for your reply. I managed to resolved the problem by adding the following to the CMakeLists.txt

CMakeLists.txt:link_directories(/home/nuaawqf/scotch_5.1.9/lib)
CMakeLists.txt:target_link_libraries(amrGem  ${MPI_LIB} ${HDF5_LIB} ${ZOLTAN_LIB} ${PARMETIS_LIBS}  libptscotch.a libscotch.a libptscotcherr.a libscotcherr.a )

I think the problem is that when linking to libZoltan.a the Cmake cannot find the scotch static libs.
